CUDA_VISIBLE_DEVICES=0 python main_c_new.py \
--dataset cifar10 \
--arch resnet18_cifar \
--depth 18 \
--lr 0.1 \
--epochs 90 \
--schedule 30 60 \
--batch-size 256 \
--test-batch-size 64 \
--save ./poisonresult_2/1_retrain/EB-70-13 \
--momentum 0.9 \
--sparsity-regularization \
--scratch ./poisonresult_2/1_pruned/EB-70-13/pruned.pth.tar \
--start-epoch 0 \
--poison_pre 1 \
--poison_method 2